/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portfolioapp;

import javax.swing.JOptionPane;

/**
 *
 * @author isabellalee
 */
public class BankGUI extends javax.swing.JFrame {

    private User user;

    /**
     * Creates new form BankGUI
     */
    public BankGUI() {
        initComponents();
    }
    public BankGUI(User user) {
        initComponents();
        this.user = user;
        String userName = user.getFirstName() + " " + user.getLastName();
        String bankNum = user.getBank().getBankNum();
        double balance = user.getBank().getBankBalance();
        
        txtAccountHolder.setText(userName);
        txtBankNum.setText(bankNum);
        txtBalance.setText(String.format("%.0f", balance));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBankAccount = new javax.swing.JLabel();
        lblAccountHolder = new javax.swing.JLabel();
        lblBankNum = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        txtAccountHolder = new javax.swing.JTextField();
        txtBankNum = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        btnUpdateBalance = new javax.swing.JButton();
        btnReturnStartScreen = new javax.swing.JButton();
        btnGoToBrokerage = new javax.swing.JButton();
        txtAddAmount = new javax.swing.JTextField();
        lblBalance$ = new javax.swing.JLabel();
        lblAddAmount$ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bank");

        lblBankAccount.setText("Bank Account");

        lblAccountHolder.setText("Account Holder");

        lblBankNum.setText("Bank Account Number");

        lblBalance.setText("Account Balance");

        btnUpdateBalance.setText("Update Balance");
        btnUpdateBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBalanceActionPerformed(evt);
            }
        });

        btnReturnStartScreen.setText("Return to Start Screen");
        btnReturnStartScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnStartScreenActionPerformed(evt);
            }
        });

        btnGoToBrokerage.setText("Go to Brokerage Account");
        btnGoToBrokerage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToBrokerageActionPerformed(evt);
            }
        });

        txtAddAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddAmountActionPerformed(evt);
            }
        });

        lblBalance$.setText("$");

        lblAddAmount$.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblBankAccount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAccountHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBankNum))
                                .addGap(0, 14, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAddAmount$, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                                    .addComponent(lblBalance$, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtAddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateBalance))
                            .addComponent(txtBalance)
                            .addComponent(txtBankNum)
                            .addComponent(txtAccountHolder))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGoToBrokerage, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                            .addComponent(btnReturnStartScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccountHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankNum)
                    .addComponent(txtBankNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalance)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBalance$))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateBalance)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAddAmount$)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoToBrokerage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReturnStartScreen)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnStartScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnStartScreenActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnReturnStartScreenActionPerformed

    private void btnUpdateBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBalanceActionPerformed
        // TODO add your handling code here:
       
        if (txtAddAmount != null && txtAddAmount.getText().length() != 0)
        {    
            user.getBank().updateBankBalance(Double.parseDouble(txtAddAmount.getText()));
            txtBalance.setText(Double.toString(user.getBank().getBankBalance()));
            txtAddAmount.setText("");
            JOptionPane.showMessageDialog(null, "Balance was Updated", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Add an Amount First", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateBalanceActionPerformed

    private void btnGoToBrokerageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToBrokerageActionPerformed
        // TODO add your handling code here:
        BrokerageGUI g = new BrokerageGUI(user);
        g.setVisible(true);
        this.dispose();   
    }//GEN-LAST:event_btnGoToBrokerageActionPerformed

    private void txtAddAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoToBrokerage;
    private javax.swing.JButton btnReturnStartScreen;
    private javax.swing.JButton btnUpdateBalance;
    private javax.swing.JLabel lblAccountHolder;
    private javax.swing.JLabel lblAddAmount$;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBalance$;
    private javax.swing.JLabel lblBankAccount;
    private javax.swing.JLabel lblBankNum;
    private javax.swing.JTextField txtAccountHolder;
    private javax.swing.JTextField txtAddAmount;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBankNum;
    // End of variables declaration//GEN-END:variables
}
