/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portfolioapp;

import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author isabellalee
 */
public class BrokerageGUI extends javax.swing.JFrame {

    DefaultListModel m1;
    LinkedList<InvestmentAsset> ilist;

    /**
     * Creates new form BrokerageGUI
     */
    public BrokerageGUI() {
        initComponents();
    }
     public BrokerageGUI(User user) {
        initComponents();
        this.user = user;
        if (user.getBrokerage().getInvestmentAssetList()!= null) {
            m1 = (DefaultListModel)(jList2.getModel());
            ilist = user.getBrokerage().getInvestmentAssetList();
            for(InvestmentAsset i: ilist) m1.addElement(i.toString());
            //===============================================================
        }
        jTextField1.setText(user.getBrokerage().getBrokerageNum());
        jTextField2.setText(Double.toString(0));
        double deposit = user.getBrokerage().getDeposit();
        user.getBrokerage().setDeposit(deposit);
        jTextField3.setText(Double.toString(user.getBrokerage().getDeposit()));
        jTextField4.setText(Double.toString(user.getBrokerage().getPortfolioValue()));
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Brokerage Account");

        jLabel1.setText("Brokerage Account Info Summary");

        jLabel2.setText("Brokerage Account Number");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Settlement Amount");

        jLabel4.setText("Deposit");

        jLabel5.setText("Portfolio Value (Total)");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jList2.setModel(new javax.swing.DefaultListModel());
        jScrollPane2.setViewportView(jList2);

        jButton1.setText("Go!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Stock");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Bond");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Foreign Currency");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Commodity");

        jButton5.setText("Put Deposit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButton1)
                            .addGap(38, 38, 38)
                            .addComponent(jRadioButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButton3)
                            .addGap(30, 30, 30)
                            .addComponent(jRadioButton4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton5)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(20, 20, 20)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton1))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //=======================================================
        ilist = user.getBrokerage().getInvestmentAssetList();
        m1.removeAllElements();
        for(InvestmentAsset i: ilist) m1.addElement(i.toString());
        //========================================================
        Double settlementAmount = user.getBrokerage().getSettlement();
        jTextField2.setText(Double.toString(settlementAmount));
        Double deposit = user.getBrokerage().getDeposit();
        jTextField3.setText(Double.toString(deposit));
        Double portfolioValue = user.getBrokerage().getPortfolioValue();
        jTextField4.setText(Double.toString(portfolioValue));
        if (user.getBrokerage().getDeposit() <= 100) {
            JOptionPane.showMessageDialog(null, "Deposit Low Alert!");
        }
             
        switch (user.getRiskPreference()) {
            case "Low":
                if (user.getBrokerage().getBondTotal() > 0.3 * (user.getBrokerage().getBondTotal()
                                                                + user.getBrokerage().getStockTotal()
                                                                + user.getBrokerage().getForeignCurrencyTotal()
                        +user.getBrokerage().getCommodityTotal()))
                {
                    JOptionPane.showMessageDialog(null, "Portfolio is Over-Conentrated in Bonds", "Warning", JOptionPane.WARNING_MESSAGE); 

                }

                if (user.getBrokerage().getStockTotal() > 0.3 * (user.getBrokerage().getBondTotal()
                                                                + user.getBrokerage().getStockTotal()
                                                                + user.getBrokerage().getForeignCurrencyTotal()
                        +user.getBrokerage().getCommodityTotal()))
                {
                    JOptionPane.showMessageDialog(null, "Portfolio is Over-Conentrated in Stocks", "Warning", JOptionPane.WARNING_MESSAGE);

                }
                if (user.getBrokerage().getForeignCurrencyTotal() > 0.3 * (user.getBrokerage().getBondTotal()
                                                                + user.getBrokerage().getStockTotal()
                                                                + user.getBrokerage().getForeignCurrencyTotal()
                        +user.getBrokerage().getCommodityTotal()))
                {
                    JOptionPane.showMessageDialog(null, "Portfolio is Over-Conentrated in Foreign Currency", "Warning", JOptionPane.WARNING_MESSAGE);
                    break;
                }
                if (user.getBrokerage().getCommodityTotal() > 0.3 * (user.getBrokerage().getBondTotal()
                                                                + user.getBrokerage().getStockTotal()
                                                                + user.getBrokerage().getForeignCurrencyTotal()
                        +user.getBrokerage().getCommodityTotal()))
                {
                    JOptionPane.showMessageDialog(null, "Portfolio is Over-Conentrated in Commodity", "Warning", JOptionPane.WARNING_MESSAGE);

                }
                break;
            case "Medium":
                if (user.getBrokerage().getBondTotal() > 0.45 * (user.getBrokerage().getBondTotal()
                                                                    + user.getBrokerage().getStockTotal()
                                                                    + user.getBrokerage().getForeignCurrencyTotal()
                            +user.getBrokerage().getCommodityTotal()))
                {
                    JOptionPane.showMessageDialog(null, "Portfolio is Over-Conentrated in Bonds", "Warning", JOptionPane.WARNING_MESSAGE);

                }

                if (user.getBrokerage().getStockTotal() > 0.45 * (user.getBrokerage().getBondTotal()
                                                                + user.getBrokerage().getStockTotal()
                                                                + user.getBrokerage().getForeignCurrencyTotal()
                        +user.getBrokerage().getCommodityTotal()))
                {
                    JOptionPane.showMessageDialog(null, "Portfolio is Over-Conentrated in Stocks", "Warning", JOptionPane.WARNING_MESSAGE);

                }
                if (user.getBrokerage().getForeignCurrencyTotal() > 0.45 * (user.getBrokerage().getBondTotal()
                                                                + user.getBrokerage().getStockTotal()
                                                                + user.getBrokerage().getForeignCurrencyTotal()
                        +user.getBrokerage().getCommodityTotal()))
                {
                    JOptionPane.showMessageDialog(null, "Portfolio is Over-Conentrated in Foreign Currency", "Warning", JOptionPane.WARNING_MESSAGE);

                }
                if (user.getBrokerage().getCommodityTotal() > 0.45 * (user.getBrokerage().getBondTotal()
                                                                + user.getBrokerage().getStockTotal()
                                                                + user.getBrokerage().getForeignCurrencyTotal()
                        +user.getBrokerage().getCommodityTotal()))
                {
                    JOptionPane.showMessageDialog(null, "Portfolio is Over-Conentrated in Commodity", "Warning", JOptionPane.WARNING_MESSAGE);

                }
             break;
            case "High":
                if (user.getBrokerage().getBondTotal() > 0.60 * (user.getBrokerage().getBondTotal()
                                                                    + user.getBrokerage().getStockTotal()
                                                                    + user.getBrokerage().getForeignCurrencyTotal()
                            +user.getBrokerage().getCommodityTotal()))
                {
                    JOptionPane.showMessageDialog(null, "Portfolio is Over-Conentrated in Bonds", "Warning", JOptionPane.WARNING_MESSAGE);

                }

                if (user.getBrokerage().getStockTotal() > 0.60 * (user.getBrokerage().getBondTotal()
                                                                + user.getBrokerage().getStockTotal()
                                                                + user.getBrokerage().getForeignCurrencyTotal()
                        +user.getBrokerage().getCommodityTotal()))
                {
                    JOptionPane.showMessageDialog(null, "Portfolio is Over-Conentrated in Stocks", "Warning", JOptionPane.WARNING_MESSAGE);

                }
                if (user.getBrokerage().getForeignCurrencyTotal() > 0.60 * (user.getBrokerage().getBondTotal()
                                                                + user.getBrokerage().getStockTotal()
                                                                + user.getBrokerage().getForeignCurrencyTotal()
                        +user.getBrokerage().getCommodityTotal()))
                {
                    JOptionPane.showMessageDialog(null, "Portfolio is Over-Conentrated in Foreign Currency", "Warning", JOptionPane.WARNING_MESSAGE);

                }
                if (user.getBrokerage().getCommodityTotal() > 0.60 * (user.getBrokerage().getBondTotal()
                                                                + user.getBrokerage().getStockTotal()
                                                                + user.getBrokerage().getForeignCurrencyTotal()
                        +user.getBrokerage().getCommodityTotal()))
                {
                    JOptionPane.showMessageDialog(null, "Portfolio is Over-Conentrated in Commodity", "Warning", JOptionPane.WARNING_MESSAGE);

                }
             break;


                  
        }
            
        JOptionPane.showMessageDialog(null, "Updated Successfully!");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        if (jRadioButton1.isSelected()) {
            StockGUI g = new StockGUI(user);
            g.setVisible(true);
        }
        else if (jRadioButton2.isSelected()) {
            BondGUI g = new BondGUI(user);
            g.setVisible(true);
        }
        if (jRadioButton3.isSelected()) {
            ForeignCurrencyGUI g = new ForeignCurrencyGUI(user);
            g.setVisible(true);
        }
        if (jRadioButton4.isSelected()) {
            CommodityGUI g = new CommodityGUI(user);
            g.setVisible(true);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //if user is risk preference, it can increase $300
        if (user.getBank().getBankBalance() > 100) {
            double orginalDeposit = user.getBrokerage().getDeposit();
            user.getBrokerage().setDeposit(orginalDeposit + 100);
            double originalBalance = user.getBank().getBankBalance();
            user.getBank().setBankBalance(originalBalance-100);
            
            JOptionPane.showMessageDialog(null, "Add $100 to your deposit");
        }
        else {
             JOptionPane.showMessageDialog(null, "Please check your bank account balance");
        }
      
       
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrokerageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrokerageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrokerageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrokerageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrokerageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
    private User user;
}
