/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portfolioapp;

import javax.swing.JOptionPane;

/**
 *
 * @author isabellalee
 */
public class RegisterGUI extends javax.swing.JFrame {

    /**
     * Creates new form RegisterGUI
     */
    public RegisterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGroupRiskPreference = new javax.swing.ButtonGroup();
        lblInstructions = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblRiskPreference = new javax.swing.JLabel();
        rbtnLowRisk = new javax.swing.JRadioButton();
        rbtnHighRisk = new javax.swing.JRadioButton();
        lblBankNum = new javax.swing.JLabel();
        txtBankNum = new javax.swing.JTextField();
        lblBrokerageNum = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtBrokerageNum = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        rbtnMediumRisk = new javax.swing.JRadioButton();
        txtPassword = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");

        lblInstructions.setText("Please Complete All Fields");

        lblFirstName.setText("First Name");

        lblRiskPreference.setText("Risk Preference");

        rbtnGroupRiskPreference.add(rbtnLowRisk);
        rbtnLowRisk.setText("Low");

        rbtnGroupRiskPreference.add(rbtnHighRisk);
        rbtnHighRisk.setText("High");

        lblBankNum.setText("Bank Account Number");

        lblBrokerageNum.setText("Brokerage Account Number");

        lblPassword.setText("User Password");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        rbtnGroupRiskPreference.add(rbtnMediumRisk);
        rbtnMediumRisk.setText("Medium");

        lblUserName.setText("Last Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(lblUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPassword)
                                    .addComponent(lblBrokerageNum))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBrokerageNum, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(txtPassword)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRiskPreference)
                                    .addComponent(lblBankNum))
                                .addGap(64, 64, 64)
                                .addComponent(txtBankNum, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(rbtnLowRisk)
                                .addGap(30, 30, 30)
                                .addComponent(rbtnMediumRisk)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnHighRisk))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInstructions)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblInstructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRiskPreference)
                    .addComponent(rbtnLowRisk)
                    .addComponent(rbtnHighRisk)
                    .addComponent(rbtnMediumRisk))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankNum)
                    .addComponent(txtBankNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrokerageNum)
                    .addComponent(txtBrokerageNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegister)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /*ButtonGroup buttonGroup = new ButtonGroup();
    buttonGroup.add(rbtnLowRisk);
    buttonGroup.add(rbtnMediumRisk);
    buttonGroup.add(rbtnHighRisk);*/
    
    
    
    
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        
        //Verify that all textfields are completed
        if (txtFirstName.getText() == null || txtFirstName.getText().length() == 0 ||
            txtLastName.getText() == null || txtLastName.getText().length() == 0 ||
            txtBankNum.getText() == null || txtBankNum.getText().length() == 0 ||
            txtBrokerageNum.getText() == null && txtBrokerageNum.getText().length() == 0 ||
            txtPassword.getText() == null || txtPassword.getText().length() == 0)
            {
                JOptionPane.showMessageDialog(null, "Information is Incomplete", "Error", JOptionPane.ERROR_MESSAGE);
            }
        //User selects low risk
        else if (rbtnLowRisk.isSelected())
            {
                PortfolioSystem.addUser(txtFirstName.getText(),txtLastName.getText(), "Low", txtBankNum.getText(),txtBrokerageNum.getText(), txtPassword.getText());
                JOptionPane.showMessageDialog(null, "Registration was Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        //User selects medium risk
        else if (rbtnMediumRisk.isSelected())
            {
                PortfolioSystem.addUser(txtFirstName.getText(),txtLastName.getText(), "Medium", txtBankNum.getText(),txtBrokerageNum.getText(), txtPassword.getText());
                JOptionPane.showMessageDialog(null, "Registration was Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        //User selects high risk
        else if (rbtnHighRisk.isSelected())
            {
                PortfolioSystem.addUser(txtFirstName.getText(),txtLastName.getText(), "High", txtBankNum.getText(),txtBrokerageNum.getText(), txtPassword.getText());
                JOptionPane.showMessageDialog(null, "Registration was Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
    }//GEN-LAST:event_btnRegisterActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblBankNum;
    private javax.swing.JLabel lblBrokerageNum;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRiskPreference;
    private javax.swing.JLabel lblUserName;
    private javax.swing.ButtonGroup rbtnGroupRiskPreference;
    private javax.swing.JRadioButton rbtnHighRisk;
    private javax.swing.JRadioButton rbtnLowRisk;
    private javax.swing.JRadioButton rbtnMediumRisk;
    private javax.swing.JTextField txtBankNum;
    private javax.swing.JTextField txtBrokerageNum;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
